### ISSUE TITLE
Linked packages are causing Babel errors

### ISSUE THREAD

**Issue by bclinkinbeard** [idyll-lang/idyll#106]
Create a simple project from scratch and run `yarn link "idyll-default-components"` (or `npm link` if you prefer). When you try to run Idyll you will get an error something like this.

Can you reproduce @mathisonian?

```
ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/bclinkinbeard/Code/idyll-lang/idyll-default-components/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/Users/bclinkinbeard/Code/idyll-lang/idyll-default-components/node_modules/regenerator-transform" (While processing preset: "/Users/bclinkinbeard/Code/idyll-lang/idyll-default-components/node_modules/babel-preset-es2015/lib/index.js")
    at /Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/bclinkinbeard/Code/idyll-lang/idyll-default-components/node_modules/babel-plugin-transform-regenerator/lib/index.js:3:18)
    at Module._compile (module.js:569:30)
    at loader (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bclinkinbeard/Code/scratch/waypoints/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by mathisonian** [comment]
can we close this?

**Comment by bclinkinbeard** [comment]
Yup
