### ISSUE TITLE
Error in command line tool

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#195]
Installed `idyll` from the beta release 0.

Steps:

```
$ npm i idyll@2.0.0-beta.0
$ touch index.idl
... add some basic markup
$ idyll index.idl

{ SyntaxError: Invalid assignment
    at JS_Parse_Error.get (eval at <anonymous> (/Users/mathisonian/projects/idyll/idyll/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (util.js:648:15)
    at formatValue (util.js:553:18)
    at inspect (util.js:186:10)
    at exports.format (util.js:72:24)
    at Console.warn (console.js:51:37)
    at pipeline.build.then.then.catch (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/src/index.js:111:21)
    at tryCatcher (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/mathisonian/projects/idyll/idyll/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
  message: 'Invalid assignment',
  filename: 0,
  line: 2984,
  col: 46,
  pos: 143896 }
```

**Comment by mathisonian** [comment]
user error
