### ISSUE TITLE
minification throwing errors

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#307]
When trying to uglify a project using the latest version of idyll, this error occurs:

```
{ Error: bundles/pages/fullscreen.js from UglifyJs
Invalid assignment [bundles/pages/fullscreen.js:90482,37]
    at /Users/mathisonian/projects/idyll/idyll/node_modules/next/dist/server/build/index.js:183:21
```

It seems that either we have a bug in our code, or we're using an ES6 feature that isn't getting transpiled correctly for uglify to consume

**Comment by mathisonian** [comment]
Some more output that could help.

This comes from running `npm run build` from a freshly generated idyll project:

```
{ SyntaxError: Name expected
    at JS_Parse_Error.get (eval at <anonymous> (/Users/mathisonian/projects/minifiii/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (util.js:658:15)
    at formatValue (util.js:561:16)
    at inspect (util.js:221:10)
    at format (util.js:98:24)
    at Console.warn (console.js:139:21)
    at pipeline.build.then.then.catch (/Users/mathisonian/projects/minifiii/node_modules/idyll/src/index.js:174:21)
    at <anonymous>
  message: 'Name expected',
  filename: 0,
  line: 28320,
  col: 6,
  pos: 929072 }
```
