### ISSUE TITLE
Show help message if the `idyll` command is run in an empty directory

### ISSUE THREAD

**Issue by mathisonian** [idyll-lang/idyll#336]
Currently if you just run 

`$ idyll` 

in an empty directory this happens:

```
mathisonian in ~/idyll-3-test
👉  idyll
Building Idyll project with output directory: build...
/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

Error: ENOENT: no such file or directory, open '/Users/mathisonian/idyll-3-test/index.idyll'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.build (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/src/pipeline/index.js:29:27)
    at IdyllInstance.build (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/src/index.js:129:16)
    at exports.handler (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/bin/cmds/build.js:38:15)
    at Object.exports.handler (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/bin/cmds/watch.js:27:3)
    at Object.self.runCommand (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/node_modules/yargs/yargs.js:1018:24)
    at Object.get [as argv] (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/Users/mathisonian/projects/idyll/idyll/packages/idyll-cli/bin/cli.js:8:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

this is probably scarier than it needs to be. We should check for the existence of the file and show a reasonable error or help message if it isn't found.

**Comment by mathisonian** [comment]
Closed by https://github.com/idyll-lang/idyll/commit/c28d4831111dc8a5db8589dc01961db1bc02aaaf
