### ISSUE TITLE
Parse error when using an alias

### ISSUE THREAD

**Issue by suhr** [idyll-lang/idyll#568]
```
Error parsing Idyll markup:
Error parsing input at line 30, column 59

[Aside]With numbers it's [Eq](0, 2, 4, 6, 7, 9, 10)[/Eq].[/Aside]
                                                        ^^^
{ Error: Error parsing input at line 30, column 59

[Aside]With numbers it's [Eq](0, 2, 4, 6, 7, 9, 10)[/Eq].[/Aside]
                                                        ^^^
    at module.exports (/home/suhr/Projects/antiscale/node_modules/idyll-compiler/dist/cjs/parser.js:18:13)
    at module.exports (/home/suhr/Projects/antiscale/node_modules/idyll-compiler/dist/cjs/index.js:42:14)
    at Object.build (/home/suhr/Projects/antiscale/node_modules/idyll/src/pipeline/index.js:33:10)
    at IdyllInstance.build (/home/suhr/Projects/antiscale/node_modules/idyll/src/index.js:115:10)
    at exports.handler.argv (/home/suhr/Projects/antiscale/node_modules/idyll/bin/cmds/build.js:80:6)
    at Object.exports.handler.argv [as handler] (/home/suhr/Projects/antiscale/node_modules/idyll/bin/cmds/watch.js:34:3)
    at Object.runCommand (/home/suhr/Projects/antiscale/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/suhr/Projects/antiscale/node_modules/yargs/yargs.js:1104:24)
    at Object.get [as argv] (/home/suhr/Projects/antiscale/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/home/suhr/Projects/antiscale/node_modules/idyll/bin/cli.js:35:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12) row: 30, column: 59 }
```

index.idyll: https://gist.github.com/suhr/dee5663f5cc6814e26928b42b7343929

package.json: https://gist.github.com/suhr/0a8e53901ad611e9a34e15e8a8109140

**Comment by mathisonian** [comment]
The compiler has some special cases for `[Equation]` tags to make sure that the code contained within isn't parsed as normal Idyll markup. We need to update these to take into account aliases to prevent the issue that @suhr is seeing. The compiler will need to be made aware of aliases and generate equivalent equation rules for them. 

See relevant code [here](https://github.com/idyll-lang/idyll/blob/master/packages/idyll-compiler/src/lexer.js#L73-L75) that has the name "equation" hard coded.
