### ISSUE TITLE
Error trying to run getting started example

### ISSUE THREAD

**Issue by yourealwaysbe** [idyll-lang/idyll#723]
**Describe the bug**
When following the "getting started" tutorial, the final "idyll" command crashes with "ERR_INVALID_ARG_TYPE". The "path" argument is undefined.

**To Reproduce**
1. Install idyll
2. Run idyll create, accepting the defaults
3. cd my-idyll-posts
4. run idyll

**Expected behavior**
The example page is created.

**Screenshots**
The given output is instead

```
node:internal/fs/utils:637
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at open (node:fs:472:10)
    at go$open (/home/matt/test/idyll/my-idyll-post/node_modules/graceful-fs/graceful-fs.js:237:14)
    at open (/home/matt/test/idyll/my-idyll-post/node_modules/graceful-fs/graceful-fs.js:234:12)
    at ReadStream$open [as open] (/home/matt/test/idyll/my-idyll-post/node_modules/graceful-fs/graceful-fs.js:186:5)
    at ReadStream._construct (node:internal/fs/streams:62:12)
    at constructNT (node:internal/streams/destroy:288:25)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: None
 - Version: idyll 5.5.1, node v15.12.0.

**Additional context**
The crash happens in the ReadStream$open function of graceful-fs.js. By this point the open function should belong to an object with a defined "path" field. Instead the object present is shown below. It looks like a file stream object, but does not have a path.

```
{"flags":"r","mode":438,"fd":null,"end":null,"bytesRead":0,"closed":false,"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[{"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":{"data":{"type":"Buffer","data":[34]},"next":null},"tail":{"data":{"type":"Buffer","data":[34]},"next":null},"length":1},"length":1,"pipes":{"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"_events":{},"_eventsCount":7,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":false,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":null},"_destroyed":false},"pipesCount":1,"flowing":true,"ended":false,"endEmitted":false,"reading":false,"sync":false,"needReadable":false,"emittedReadable":true,"readableListening":false,"resumeScheduled":true,"destroyed":false,"defaultEncoding":"utf8","awaitDrain":0,"readingMore":true,"decoder":null,"encoding":null},"readable":true,"_events":{"end":[null,null]},"_eventsCount":7,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":true,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"allowHalfOpen":true,"_transformState":{"needTransform":false,"transforming":false,"writecb":null,"writechunk":null,"writeencoding":null},"_destroyed":false}],"flowing":true,"ended":false,"endEmitted":false,"reading":false,"constructed":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":true,"errorEmitted":false,"emitClose":true,"autoDestroy":true,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":{"encoding":"utf8"},"encoding":"utf8"},"_events":{},"_eventsCount":4}
```
It looks a bit like #680, but happens even if i empty index.idyll, and is not fixed in 5.5.1.

**Comment by mathisonian** [comment]
Thanks for reporting this @yourealwaysbe. I agree it seems related to #680 and the Node 15 issues. 

Is there any difference if you start the project by running `npm start` instead of `idyll`? And I assume the issue goes away if you run it under node v14?

**Comment by johanna-einsiedler** [comment]
Running into the same error - interestingly only for the multipage setup, single blogpost works fine for me.

**Comment by mathisonian** [comment]
Thanks for the reports @johanna-einsiedler @yourealwaysbe. I tracked this down to an issue in [brfs](https://github.com/browserify/brfs/pull/96) and released a patched version. I confirmed that the `article` and `multipage` template are working correctly on node v15 on macos. 

The fix is available in `idyll@5.5.2` on npm. When updating make sure to upgrade your global idyll `npm i -g idyll@latest` as well as the local copy in any projects `npm i --save idyll@latest`. 

Please comment if you are still experiencing issues and we can reopen.

**Comment by johanna-einsiedler** [comment]
Thank you so much - works perfectly now!

**Comment by yourealwaysbe** [comment]
Works for me too, thanks!
